# Generated by Django 5.1.5 on 2025-04-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank='True', null='True', upload_to='product_image'),
        ),
    ]
